# Generated by Django 3.1 on 2022-02-04 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quality',
            new_name='quantity',
        ),
    ]
